default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: levelup_development

test:
  <<: *default
  database: levelup_test

production:
  <<: *default
  database: levelup_production
  username: levelup
  password: <%= ENV['LEVELUP_DATABASE_PASSWORD'] %>
