default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: levelup_development

test:
  <<: *default
  database: levelup_test

production:
  <<: *default
  database: levelup_production
  username: levelup
  password: <%= ENV['LEVELUP_DATABASE_PASSWORD'] %>
