# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d08af7348356caf6d78b6cbe1bf174abd88e4383ad51f5c746d69a9bdea50776de77fa1661812f176697a388829d8f464bac0df0d1fcdb48c499a70c8da94b

test:
  secret_key_base: 1f4f2afb6bc661848ebcff5c06ad34acfda215bd1dfaba9897116f3129123c78e235c3a9425777f366fc1b9f2aa4dadf4da5c2cf248116823dc4f923a033cb14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
